[workspace]
members = ["cargo:crates/ry-cli"]

[dist]
cargo-dist-version = "0.32.0"
ci = "github"
create-release = true
installers = ["shell", "powershell"]
windows-archive = ".zip"
unix-archive = ".tar.gz"
targets = [
  "x86_64-apple-darwin",
  "aarch64-apple-darwin",
  "x86_64-pc-windows-msvc",
  "aarch64-pc-windows-msvc",
  "x86_64-unknown-linux-gnu",
  "aarch64-unknown-linux-gnu",
]
precise-builds = true
auto-includes = false
pr-run-mode = "skip"
dispatch-releases = true
install-path = ["$XDG_BIN_HOME/", "$XDG_DATA_HOME/../bin", "~/.local/bin"]
install-updater = false

[dist.github-custom-runners]
global = "ubuntu-latest"

[dist.github-custom-runners.x86_64-apple-darwin]
runner = "macos-15"

[dist.github-custom-runners.aarch64-apple-darwin]
runner = "macos-14"

[dist.github-custom-runners.x86_64-pc-windows-msvc]
runner = "windows-2022"

[dist.github-custom-runners.aarch64-pc-windows-msvc]
runner = "ubuntu-latest"
host = "x86_64-unknown-linux-gnu"
container = { image = "messense/cargo-xwin", host = "x86_64-unknown-linux-musl", package_manager = "apt" }
